influxdb:
  bucket: "Gait/autogen"
  org: "UPM"
  token: "PON_TU_TOKEN_AQUI"
  url: "https://TU_IP_O_LOCALHOST:8086/"

params:
  freq_target_hz: 75
  freq_psd_hz: 20
  fact_hz: 4.0
  f_start_hz: 0.0
  f_stop_hz: 7.0
  window_overlap: 0.90

Location:
  proj: 'utm'
  zone: 30
  ellps: 'WGS84'
  south: False
  code: 'epsg:4326'
  zoneInfo: 'Europe/Madrid'

Display:
  mode: 'Screen'

io:
  excel: "solicitud.xlsx"   # ARCHIVO DE ENTRADA
  out: "resultados"         # CARPETA DE SALIDA
